# Generated by Django 5.0.3 on 2024-03-23 14:53

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_tag_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apis.models.product_image_upload_path),
        ),
    ]
